(function(){
  'use strict';
  if(sessionStorage.getItem('wmUserMirrorVersion')!=='2'){sessionStorage.removeItem('wmPublicProfilesRebuilt');sessionStorage.setItem('wmUserMirrorVersion','2')}
  let adminUser=null,adminProfile={},users=[],publicProfiles={},subscriptions={},payments=[],pricing={normal:5,discount:3.8},adminAvailable=true,view='overview',selectedUid=null,listenersStarted=false,badgeSequence=0;
  const grantPricingStamped=new Set(),emailRecoveryStamped=new Set();let supporterNumbersBackfilled=false,supporterNumbersBusy=false,usernameReservationsBackfilled=false,usernameReservationsBusy=false;
  const safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const validImageUrl=value=>/^(?:https?:\/\/|\.{0,2}\/|[A-Za-z0-9_./-]+\.(?:png|jpe?g|webp|gif|svg)(?:[?#].*)?)$/i.test(String(value||''));
  const fullDate=value=>value?new Date(Number(value)).toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric'}):'—';
  const fullDateTime=value=>value?new Date(Number(value)).toLocaleString('en-MY',{day:'2-digit',month:'long',year:'numeric',hour:'numeric',minute:'2-digit',hour12:true}):'—';
  const monthDate=value=>value?new Date(Number(value)).toLocaleDateString('en-GB',{month:'long',year:'numeric'}):'—';
  const dateValue=value=>{const number=Number(value);if(Number.isFinite(number)&&number>0)return number;const parsed=Date.parse(value);return Number.isFinite(parsed)?parsed:0};
  const earliestDate=(...values)=>{const valid=values.map(dateValue).filter(Boolean);return valid.length?Math.min(...valid):0};
  const compact=value=>value>=1000000?(value/1000000).toFixed(value%1000000?1:0).replace('.0','')+'M':value>=10000?(value/1000).toFixed(value%1000?1:0).replace('.0','')+'k':Number(value||0).toLocaleString('en-US');
  const planFor=uid=>WMFirebase.effectivePlan(subscriptions[uid]);
  async function nextSupporterNumber(existing){if(Number(existing)>0)return Number(existing);return Math.max(0,...Object.values(subscriptions).map(sub=>Number(sub?.supporterNumber||0)))+1}
  async function backfillSupporterNumbers(){if(!adminUser||supporterNumbersBackfilled||supporterNumbersBusy)return;const ordered=Object.entries(subscriptions).filter(([,sub])=>Number(sub?.proSince||0)>0).sort((a,b)=>Number(a[1].proSince)-Number(b[1].proSince));if(!ordered.length)return;supporterNumbersBusy=true;try{const updates={};ordered.forEach(([uid,sub],index)=>{if(!(Number(sub.supporterNumber)>0))updates['subscriptions/'+uid+'/supporterNumber']=index+1});if(Object.keys(updates).length)await WMFirebase.db.ref().update(updates);supporterNumbersBackfilled=true}catch(error){console.warn('Supporter numbering deferred:',error.code||error.message)}finally{supporterNumbersBusy=false}}
  const mobileName=name=>matchMedia('(max-width:720px)').matches&&name.length>=13?name.slice(0,8)+'..'+name.charAt(name.length-1):name;
  const cloneBadge=()=>{const source=document.querySelector('.verified-badge');if(!source)return '';const clone=source.cloneNode(true),clip=clone.querySelector('clipPath'),image=clone.querySelector('image');clone.removeAttribute('onclick');clone.classList.add('clickable');if(clip&&image){const id='adminLiveBadge'+(++badgeSequence);clip.id=id;image.setAttribute('clip-path','url(#'+id+')')}return clone.outerHTML};
  const avatar=(user,cls='admin-avatar')=>user.avatarUrl?'<div class="'+cls+'"><img src="'+safe(user.avatarUrl)+'" alt=""></div>':'<div class="'+cls+'"><span class="avatar-letter">'+safe((user.name||'U').charAt(0))+'</span></div>';
  const confirmModal=document.createElement('div');confirmModal.className='admin-confirm-overlay';confirmModal.innerHTML='<div class="admin-confirm-card"><h3></h3><p></p><div><button class="admin-confirm-cancel" type="button">Cancel</button><button class="admin-confirm-accept" type="button">Confirm</button></div></div>';document.body.appendChild(confirmModal);let confirmResolver=null;function askAdminConfirm(title,message,action='Confirm'){confirmModal.querySelector('h3').textContent=title;confirmModal.querySelector('p').textContent=message;confirmModal.querySelector('.admin-confirm-accept').textContent=action;confirmModal.classList.add('show');return new Promise(resolve=>{confirmResolver=resolve})}function closeAdminConfirm(value){confirmModal.classList.remove('show');if(confirmResolver){confirmResolver(value);confirmResolver=null}}confirmModal.querySelector('.admin-confirm-cancel').onclick=()=>closeAdminConfirm(false);confirmModal.querySelector('.admin-confirm-accept').onclick=()=>closeAdminConfirm(true);confirmModal.onclick=event=>{if(event.target===confirmModal)closeAdminConfirm(false)};
  function findAdminBlock(title){const label=[...document.querySelectorAll('.demo-label h2')].find(node=>node.textContent.trim()===title)?.parentElement;if(!label)return null;let node=label.nextElementSibling;while(node&&!node.classList.contains('admin'))node=node.nextElementSibling;return node}
  function createShell(){
    const header=document.createElement('header');header.className='admin-live-header';header.innerHTML='<div class="admin-live-header-inner"><button class="admin-live-brand" type="button" aria-label="Open dashboard"><img src="logo.png" alt=""><strong>Watermark Pro</strong></button><div class="admin-live-identity" id="adminLiveIdentity"></div><button class="admin-live-menu-button" type="button" aria-label="Open menu"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button></div><nav class="admin-live-menu" hidden><button data-admin-view="overview">Dashboard</button><button data-admin-view="settings">Settings</button><button data-admin-view="logout">Logout</button></nav>';document.body.prepend(header);
    const root=document.createElement('div');root.className='admin-live-root admin-only';document.querySelector('.container').appendChild(root);
    const backLink=document.querySelector('.back-app');if(backLink){backLink.textContent='Back to Watermark Tools';backLink.href='index.html'}
    const blocks={overview:findAdminBlock('Admin — Dashboard'),subscriptions:findAdminBlock('Admin — Subscription & Payment Review'),top:findAdminBlock('Admin — Top Users'),users:findAdminBlock('Admin — User Details')};
    const dashboardNav=blocks.overview?.querySelector('.admin-nav');if(dashboardNav){dashboardNav.classList.add('admin-live-dashboard-nav');dashboardNav.querySelectorAll('button').forEach(button=>{const label=button.textContent.trim();button.dataset.adminView=label==='Top Users'?'top':label.toLowerCase()});root.appendChild(dashboardNav)}
    Object.entries(blocks).forEach(([key,block])=>{if(block){block.classList.add('admin-live-section');block.dataset.adminSection=key;root.appendChild(block)}});
    const settings=document.createElement('section');settings.className='admin admin-live-section admin-live-settings-section';settings.dataset.adminSection='settings';settings.innerHTML='<div class="admin-live-settings-card"><h3>Settings</h3><div class="admin-live-setting"><div><div class="admin-live-setting-label">Profile Avatar</div><div class="admin-live-setting-value">Use a direct image URL.</div></div><div class="admin-live-setting-action"><div class="admin-live-avatar" id="adminProfileAvatar"></div><input id="adminProfileAvatarUrl" placeholder="https://example.com/avatar.jpg"></div></div><div class="admin-live-setting"><div><div class="admin-live-setting-label">Username</div></div><input id="adminProfileUsername" maxlength="20"></div><div class="admin-live-setting"><div><div class="admin-live-setting-label">Email Address</div></div><div class="admin-live-setting-value" id="adminProfileEmail"></div></div><div class="admin-live-setting"><div><div class="admin-live-setting-label">Created At</div></div><div class="admin-live-setting-value" id="adminProfileCreated"></div></div><div class="admin-live-setting"><div><div class="admin-live-setting-label">Role</div></div><span class="admin-live-role">ADMIN</span></div><button class="admin-live-settings-save" id="adminProfileSave">Save Settings</button></div>';root.appendChild(settings);
    settings.querySelector('.admin-live-settings-save').insertAdjacentHTML('beforebegin','<div class="admin-live-setting admin-availability-setting"><div><div class="admin-live-setting-label">Payment Approval Availability</div><div class="admin-live-setting-value">Turn this off whenever you cannot review or approve payments.</div></div><button class="admin-availability-toggle" id="adminAvailabilityToggle" type="button"><i></i><span>Available</span></button></div>');
    document.getElementById('adminAvailabilityToggle').onclick=async()=>{const button=document.getElementById('adminAvailabilityToggle');button.disabled=true;try{await WMFirebase.db.ref('settings/adminAvailable').set(!adminAvailable)}finally{button.disabled=false}};
    const imageViewer=document.createElement('div');imageViewer.className='wm-image-viewer';imageViewer.innerHTML='<img alt="Image preview">';document.body.appendChild(imageViewer);imageViewer.onclick=()=>imageViewer.classList.remove('show');document.addEventListener('click',event=>{const image=event.target.closest('img');if(!image||image.closest('.website-supporter-card-section,.wm-image-viewer')||!image.currentSrc)return;event.preventDefault();event.stopPropagation();imageViewer.querySelector('img').src=image.currentSrc;imageViewer.classList.add('show')},true);
    const price=blocks.subscriptions?.querySelector('.price-settings'),qr=blocks.subscriptions?.querySelector('.qr-update-box');if(price)settings.appendChild(price);if(qr)settings.appendChild(qr);
    if(backLink)root.appendChild(backLink);
    if(blocks.users){blocks.users.querySelector('.admin-content').innerHTML='<div class="admin-live-users-list" id="adminLiveUsers"><div class="admin-live-empty">Loading users…</div></div>'}
    if(blocks.top){const top=blocks.top.querySelector('.admin-top');if(top)top.innerHTML='<div class="admin-top-title">Top Users</div><div id="adminLiveTopUsers"><div class="admin-live-top-empty">Loading ranking…</div></div>'}
    dashboardNav?.querySelectorAll('button').forEach(button=>{button.removeAttribute('onclick');button.onclick=event=>{event.preventDefault();showView(button.dataset.adminView)}});
    const menu=header.querySelector('.admin-live-menu');header.querySelector('.admin-live-menu-button').onclick=event=>{event.stopPropagation();menu.hidden=!menu.hidden};menu.onclick=event=>{event.stopPropagation();const target=event.target.dataset.adminView;if(!target)return;menu.hidden=true;if(target==='logout'){stopAdminListeners();WMFirebase.auth.signOut();return}showView(target)};document.addEventListener('click',()=>menu.hidden=true);
    header.querySelector('.admin-live-brand').onclick=()=>showView('overview');
    document.getElementById('adminProfileSave').onclick=saveAdminProfile;
    const refreshAdminAvatarPreview=()=>{const value=document.getElementById('adminProfileAvatarUrl').value.trim(),name=document.getElementById('adminProfileUsername').value.trim()||adminProfile.username||adminUser?.displayName||'A',preview=document.getElementById('adminProfileAvatar'),letter=name.charAt(0);preview.textContent=letter;if(value&&validImageUrl(value)){const image=document.createElement('img');image.alt='';image.onload=()=>preview.replaceChildren(image);image.onerror=()=>{preview.textContent=letter};image.src=value}};document.getElementById('adminProfileAvatarUrl').addEventListener('input',refreshAdminAvatarPreview);document.getElementById('adminProfileUsername').addEventListener('input',refreshAdminAvatarPreview);
    const authCard=document.querySelector('.admin-auth-card');if(authCard&&!authCard.querySelector('.admin-auth-card-brand'))authCard.insertAdjacentHTML('afterbegin','<div class="admin-auth-card-brand"><img src="logo.png" alt=""><strong>Watermark Pro</strong></div>');
    document.querySelector('#adminAuthForm h2').textContent='Admin Login';
    document.getElementById('grantUser')?.setAttribute('placeholder','Enter email or username');
    const grantLabel=document.querySelector('#grantUser')?.previousElementSibling;if(grantLabel)grantLabel.textContent='Email / Username';
    window.grantFreePro=grantFreeProLive;
    WMFirebase.db.ref('publicProfiles').on('value',snapshot=>{publicProfiles=snapshot.val()||{};Object.entries(publicProfiles).forEach(([uid,profile])=>{if(!users.some(user=>user.uid===uid))users.push({uid,...profile,email:profile.email||''})});users.sort((a,b)=>String(a.name||'').localeCompare(String(b.name||'')));renderAll()});
    setInterval(()=>{let changed=false;Object.entries(publicProfiles).forEach(([uid,profile])=>{if(!users.some(user=>user.uid===uid)){users.push({uid,...profile,email:profile.email||''});changed=true}});if(changed){users.sort((a,b)=>String(a.name||'').localeCompare(String(b.name||'')));renderAll()}},750);
  }
  function showView(next){view=['overview','users','subscriptions','top','settings'].includes(next)?next:'overview';document.documentElement.classList.toggle('admin-settings-view',view==='settings');document.querySelectorAll('.admin-live-section').forEach(section=>section.classList.toggle('active',section.dataset.adminSection===view));document.querySelectorAll('.admin-live-dashboard-nav button').forEach(button=>button.classList.toggle('active',button.dataset.adminView===view));history.replaceState({adminView:view},'',location.pathname+location.search+'#'+view);scrollTo({top:0,behavior:'smooth'});renderAll()}
  function renderIdentity(){const root=document.getElementById('adminLiveIdentity');if(!root||!adminUser)return;const name=adminProfile.username||adminUser.displayName||adminUser.email.split('@')[0];root.innerHTML=(adminProfile.avatarUrl?'<div class="admin-live-avatar"><img src="'+safe(adminProfile.avatarUrl)+'" alt=""></div>':'<div class="admin-live-avatar">'+safe(name.charAt(0))+'</div>')+'<span>'+safe(name)+'</span>';root.setAttribute('role','button');root.tabIndex=0;root.onclick=()=>showView('settings');root.onkeydown=event=>{if(event.key==='Enter'||event.key===' ')showView('settings')}}
  function openAdminVerified(user){openBadgeModal(user.name||'User',(user.name||'U').charAt(0),user.avatarUrl||null,fullDate(subscriptions[user.uid]?.proSince));const sub=document.getElementById('badgeModalSub');if(sub)sub.textContent=(user.name||'User')+' is a verified Pro Supporter. Their verified identity is shown publicly beside their username.'}
  function bindBadges(root,userMap){root.querySelectorAll('[data-verified-uid]').forEach(badge=>{badge.onclick=()=>openAdminVerified(userMap[badge.dataset.verifiedUid])})}
  function renderOverview(){const root=document.querySelector('[data-admin-section="overview"]');if(!root)return;const stats=root.querySelectorAll('.admin-stat strong'),active=users.filter(user=>planFor(user.uid)==='pro'),expiring=active.filter(user=>Number(subscriptions[user.uid]?.expiresAt||0)-Date.now()<=7*86400000),downloads=users.reduce((sum,user)=>sum+Number(user.downloads||0),0);if(stats[0])stats[0].textContent=users.length.toLocaleString();if(stats[1])stats[1].textContent=active.length.toLocaleString();if(stats[2])stats[2].textContent=expiring.length.toLocaleString();if(stats[3])stats[3].textContent=downloads.toLocaleString();const table=root.querySelector('.admin-table');if(!table)return;table.innerHTML='<div class="admin-row-overview admin-head"><div class="ov-user">User</div><div class="ov-dl">Downloads</div><div class="ov-plan">Plan</div><div class="status-right">Status</div></div>'+[...users].sort((a,b)=>Number(b.downloads||0)-Number(a.downloads||0)).slice(0,20).map(user=>{const plan=planFor(user.uid),days=plan==='pro'?Math.ceil((Number(subscriptions[user.uid].expiresAt)-Date.now())/86400000):0,status=plan==='pro'?(days<=7?'expiring':'active'):plan==='expired_free'?'expired':'free',label=plan==='pro'?(days<=7?'EXPIRING':'ACTIVE'):plan==='expired_free'?'EXPIRED':'FREE',badge=plan==='pro'?cloneBadge():'';return '<div class="admin-row-overview"><div class="ov-user admin-user">'+avatar(user)+'<div class="admin-name"><span>'+safe(mobileName(user.name||'User'))+'</span>'+(badge?badge.replace('class="verified-badge clickable"','class="verified-badge clickable" data-verified-uid="'+safe(user.uid)+'"'):badge)+'</div></div><div class="ov-dl">'+compact(Number(user.downloads||0))+'</div><div class="ov-plan">'+(plan==='pro'?'Pro':'Free')+'</div><div class="status-right"><span class="admin-status '+status+'">'+label+'</span></div></div>'}).join('');bindBadges(table,Object.fromEntries(users.map(user=>[user.uid,user])))}
  function renderUsers(){
    const root=document.getElementById('adminLiveUsers');if(!root)return;
    root.innerHTML=users.length?users.map(user=>'<div class="admin-live-user-row" data-user-row="'+safe(user.uid)+'"><div class="admin-live-user-main">'+avatar(user)+'<div class="admin-live-user-text"><div class="admin-live-user-name"><span>'+safe(user.name||'User')+'</span></div><div class="admin-live-user-email">'+safe(user.email||'')+'</div></div></div><button class="admin-edit-button" data-edit-user="'+safe(user.uid)+'">Edit Details</button>'+(selectedUid===user.uid?detailsMarkup(user):'')+'</div>').join(''):'<div class="admin-live-empty">No users found.</div>';
    root.querySelectorAll('[data-user-row]').forEach(row=>{const user=users.find(item=>item.uid===row.dataset.userRow);if(!user||planFor(user.uid)!=='pro')return;const name=row.querySelector('.admin-live-user-name');name.insertAdjacentHTML('beforeend',cloneBadge().replace('class="verified-badge clickable"','class="verified-badge clickable" data-verified-uid="'+safe(user.uid)+'"'))});bindBadges(root,Object.fromEntries(users.map(user=>[user.uid,user])));
    root.querySelectorAll('[data-edit-user]').forEach(button=>button.onclick=()=>{selectedUid=selectedUid===button.dataset.editUser?null:button.dataset.editUser;renderUsers()});
    const save=root.querySelector('[data-save-user]');if(save)save.onclick=saveSelectedUser;
    root.querySelector('[data-remove-pro]')?.addEventListener('click',removeSelectedPro);
    root.querySelector('[data-cancel-user]')?.addEventListener('click',()=>{selectedUid=null;renderUsers()});
    const avatarInput=root.querySelector('#editUserAvatar');if(avatarInput){const user=users.find(item=>item.uid===selectedUid),preview=document.createElement('div');preview.className='admin-edit-avatar-preview';avatarInput.before(preview);const updatePreview=()=>{const value=avatarInput.value.trim(),letter=(root.querySelector('#editUserName')?.value||user?.name||'U').charAt(0);preview.textContent=letter;if(value&&validImageUrl(value)){const image=document.createElement('img');image.alt='';image.onload=()=>preview.replaceChildren(image);image.onerror=()=>{preview.textContent=letter};image.src=value}};avatarInput.addEventListener('input',updatePreview);root.querySelector('#editUserName')?.addEventListener('input',updatePreview);updatePreview()}
    root.querySelectorAll('[data-admin-receipt]').forEach(button=>button.onclick=()=>{const payment=payments.find(item=>item.id===button.dataset.adminReceipt),user=users.find(item=>item.uid===payment?.uid);if(!payment||!user)return;const original=Number(payment.originalPrice||pricing.normal),paid=Number(payment.amount||0);openReceipt(user.name||'User',payment.reference||payment.id,fullDateTime(payment.submittedAt||payment.approvedAt),'RM'+original.toFixed(2),'RM'+Math.max(0,original-paid).toFixed(2),'RM'+paid.toFixed(2),fullDateTime(payment.submittedAt||payment.approvedAt),true,String(payment.status||'pending').toLowerCase(),fullDateTime(payment.expiresAt))});
    root.querySelectorAll('[data-admin-grant-receipt]').forEach(button=>button.onclick=()=>{const user=users.find(item=>item.uid===button.dataset.adminGrantReceipt),sub=user?subscriptions[user.uid]||{}:{};if(!user)return;const months=Math.max(1,Number(sub.grantedMonths||1)),monthly=Number(sub.monthlyPrice||pricing.normal||5),subtotal=Number(sub.grantedSubtotal||months*monthly),date=fullDateTime(sub.approvedAt||sub.proSince);openReceipt(user.name||'User','GRANT-'+user.uid.slice(0,8).toUpperCase(),date,'RM'+subtotal.toFixed(2),'RM'+subtotal.toFixed(2),'RM0.00',date,true,'granted',fullDateTime(sub.expiresAt),'Pro Supporter · '+months+' month'+(months===1?'':'s'))});
  }
  function detailsMarkup(user){
    const sub=subscriptions[user.uid]||{},plan=planFor(user.uid),history=payments.filter(payment=>payment.uid===user.uid).sort((a,b)=>Number(b.submittedAt||0)-Number(a.submittedAt||0));
    const paidRows=history.map(payment=>'<div class="admin-live-history-row"><div><strong>'+(payment.kind==='renewal'?'Pro Supporter renewal':'Pro Supporter · 1 month')+'</strong><small>'+fullDate(payment.submittedAt)+' · '+safe(payment.reference||payment.id)+'</small></div><div class="admin-live-history-actions"><span class="admin-status '+(payment.status==='paid'?'active':payment.status==='rejected'?'expired':'pending')+'">'+safe(String(payment.status||'pending').toUpperCase())+'</span><button class="btn-receipt" data-admin-receipt="'+safe(payment.id)+'">Receipt</button></div></div>');
    if(sub.source==='free_grant'){const months=Math.max(1,Number(sub.grantedMonths||1));paidRows.push('<div class="admin-live-history-row"><div><strong>Pro Supporter · '+months+' month'+(months===1?'':'s')+'</strong><small>'+fullDate(sub.approvedAt||sub.proSince)+' – '+fullDate(sub.expiresAt)+' · GRANT-'+safe(user.uid.slice(0,8).toUpperCase())+'</small></div><div class="admin-live-history-actions"><span class="admin-status active">GRANTED</span><button class="btn-receipt" data-admin-grant-receipt="'+safe(user.uid)+'">Receipt</button></div></div>')}
    const historyHtml=paidRows.length?paidRows.join(''):'<div class="admin-live-empty">No subscription history.</div>';
    return '<div class="admin-live-details"><div class="admin-live-details-title"><strong>User Details</strong><span class="admin-status '+(plan==='pro'?'active':plan==='expired_free'?'expired':'free')+'">'+(plan==='pro'?'PRO SUPPORTER':plan==='expired_free'?'PRO EXPIRED':'FREE')+'</span></div><div class="admin-live-details-grid"><div><label class="admin-label">Username</label><input id="editUserName" maxlength="20" value="'+safe(user.name||'')+'"></div><div><label class="admin-label">Email</label><input id="editUserEmail" type="email" value="'+safe(user.email||'')+'"></div><div class="wide"><label class="admin-label">Avatar Image URL</label><input id="editUserAvatar" value="'+safe(user.avatarUrl||'')+'" placeholder="https://example.com/avatar.jpg"></div></div><div class="admin-live-meta"><div><span>Account Created</span><strong>'+fullDate(earliestDate(publicProfiles[user.uid]?.accountCreatedAt,user.accountCreatedAt,user.createdAt,user.created,user.joinedAt))+'</strong></div><div><span>Downloads</span><strong>'+Number(user.downloads||0).toLocaleString()+'</strong></div><div><span>'+(plan==='pro'?'Pro Since':'Account Plan')+'</span><strong>'+(plan==='pro'?fullDate(sub.proSince):plan==='expired_free'?'Expired Pro':'Free')+'</strong></div></div><div class="admin-live-history"><h4>Subscription History</h4>'+historyHtml+'</div><div class="admin-live-details-actions">'+(plan==='pro'?'<button class="admin-live-remove-pro" data-remove-pro>Remove Pro</button>':'')+'<button class="admin-live-delete" data-delete-user>Delete User</button><button class="admin-live-cancel" data-cancel-user>Cancel</button><button class="admin-live-save" data-save-user>Save User Details</button></div></div>';
  }
  async function saveSelectedUser(){const user=users.find(item=>item.uid===selectedUid);if(!user)return;const button=document.querySelector('[data-save-user]'),name=document.getElementById('editUserName').value.trim(),email=document.getElementById('editUserEmail').value.trim().toLowerCase(),avatarUrl=document.getElementById('editUserAvatar').value.trim();button.disabled=true;const oldKey=WMFirebase.usernameKey(user.name),newKey=WMFirebase.usernameKey(name);let reserved=false;try{if(!/^[A-Za-z0-9._]{2,20}$/.test(name))throw new Error('Username must contain 2–20 letters, numbers, dots or underscores.');if(!/^\S+@\S+\.\S+$/.test(email))throw new Error('Enter a valid email address.');if(avatarUrl&&!validImageUrl(avatarUrl))throw new Error('Enter a valid avatar image URL or local image filename.');if(users.some(item=>item.uid!==user.uid&&String(item.name||'').trim().toLowerCase()===name.toLowerCase()))throw new Error('This username is already in use.');if(newKey!==oldKey){const claim=await WMFirebase.db.ref('usernames/'+newKey).transaction(current=>current===null||current===user.uid?user.uid:undefined);if(!claim.committed)throw new Error('This username is already in use.');reserved=true}await WMFirebase.db.ref().update({['users/'+user.uid+'/name']:name,['users/'+user.uid+'/email']:email,['users/'+user.uid+'/avatarUrl']:avatarUrl,['publicProfiles/'+user.uid+'/name']:name,['publicProfiles/'+user.uid+'/avatarUrl']:avatarUrl});if(reserved&&oldKey){const oldRef=WMFirebase.db.ref('usernames/'+oldKey),oldValue=(await oldRef.once('value')).val();if(oldValue===user.uid)await oldRef.remove()}showToast('User details updated');selectedUid=null;renderUsers()}catch(error){if(reserved)await WMFirebase.db.ref('usernames/'+newKey).remove().catch(()=>{});showToast(String(error.message||'Unable to update user').replace(/^Firebase:\s*/i,''));button.disabled=false}}
  async function removeSelectedPro(){const user=users.find(item=>item.uid===selectedUid),sub=user?subscriptions[user.uid]||{}:{};if(!user||!await askAdminConfirm('Remove Pro Supporter','Return '+(user.name||'this user')+' to the Free plan? Their Pro history will remain visible.','Remove Pro'))return;const now=Date.now(),button=document.querySelector('[data-remove-pro]');button.disabled=true;try{await WMFirebase.db.ref().update({['subscriptions/'+user.uid+'/status']:'expired_free',['subscriptions/'+user.uid+'/expiresAt']:now,['subscriptions/'+user.uid+'/removedAt']:now,['users/'+user.uid+'/proExpiresAt']:now,['publicProfiles/'+user.uid+'/proExpiresAt']:now});showToast('Pro Supporter access removed');renderUsers()}catch(error){showToast(error.message||'Unable to remove Pro');button.disabled=false}}
  function renderTop(){const root=document.getElementById('adminLiveTopUsers');if(!root)return;const ranked=[...users].sort((a,b)=>Number(b.downloads||0)-Number(a.downloads||0)).slice(0,20),map=Object.fromEntries(users.map(user=>[user.uid,user]));root.innerHTML=ranked.length?ranked.map((user,index)=>{const pro=planFor(user.uid)==='pro',badge=pro?cloneBadge():'';return '<div class="admin-top-row"><div class="top-rank">#'+(index+1)+'</div><div class="top-user admin-user">'+avatar(user)+'<div class="admin-name"><span>'+safe(mobileName(user.name||'User'))+'</span>'+(badge?badge.replace('class="verified-badge clickable"','class="verified-badge clickable" data-verified-uid="'+safe(user.uid)+'"'):badge)+'</div></div><div class="top-dl">'+compact(Number(user.downloads||0))+' downloads</div><div class="top-vis '+(user.showOnTopUsers===false?'visibility-off':'visibility-on')+'">'+(user.showOnTopUsers===false?'HIDDEN':'PUBLIC')+'</div></div>'}).join(''):'<div class="admin-live-top-empty">No ranking data yet.</div>';bindBadges(root,map)}
  function renderSubscriptions(){const stats=document.querySelectorAll('#subscriptionStats .admin-stat strong'),active=users.filter(user=>planFor(user.uid)==='pro'),expiring=active.filter(user=>Number(subscriptions[user.uid]?.expiresAt||0)-Date.now()<=7*86400000),pending=payments.filter(payment=>payment.status==='pending'),now=new Date(),monthly=payments.filter(payment=>payment.status==='paid'&&new Date(Number(payment.approvedAt||payment.submittedAt)).getMonth()===now.getMonth()&&new Date(Number(payment.approvedAt||payment.submittedAt)).getFullYear()===now.getFullYear()).reduce((sum,payment)=>sum+Number(payment.amount||0),0);if(stats[0])stats[0].textContent=active.length;if(stats[1])stats[1].textContent=expiring.length;if(stats[2])stats[2].textContent=pending.length;if(stats[3])stats[3].textContent='RM'+monthly.toFixed(2)}
  function renderSettings(){if(!adminUser)return;const name=adminProfile.username||adminUser.displayName||adminUser.email.split('@')[0],avatarUrl=adminProfile.avatarUrl||adminUser.photoURL||'';document.getElementById('adminProfileUsername').value=name;document.getElementById('adminProfileAvatarUrl').value=avatarUrl;document.getElementById('adminProfileEmail').textContent=adminUser.email||'';document.getElementById('adminProfileCreated').textContent=fullDate(adminUser.metadata?.creationTime?Date.parse(adminUser.metadata.creationTime):0);const avatarRoot=document.getElementById('adminProfileAvatar');avatarRoot.innerHTML=avatarUrl?'<img src="'+safe(avatarUrl)+'" alt="">':safe(name.charAt(0));document.getElementById('normalPrice').value=Number(pricing.normal).toFixed(2);document.getElementById('discountPrice').value=Number(pricing.discount)>0&&Number(pricing.discount)<Number(pricing.normal)?Number(pricing.discount).toFixed(2):''}
  async function saveAdminProfile(){const username=document.getElementById('adminProfileUsername').value.trim(),avatarUrl=document.getElementById('adminProfileAvatarUrl').value.trim();if(!/^[A-Za-z0-9._]{2,20}$/.test(username)){showToast('Username must contain 2–20 letters, numbers, dots or underscores.');return}if(avatarUrl&&!validImageUrl(avatarUrl)){showToast('Enter a valid avatar image URL or local image filename.');return}const oldUsername=adminProfile.username||adminUser.displayName||'',oldKey=WMFirebase.usernameKey(oldUsername),newKey=WMFirebase.usernameKey(username);let reserved=false;try{if(newKey!==oldKey){const result=await WMFirebase.db.ref('usernames/'+newKey).transaction(current=>current===null||current===adminUser.uid?adminUser.uid:undefined);if(!result.committed)throw new Error('This username is already in use.');reserved=true}await adminUser.updateProfile({displayName:username,photoURL:avatarUrl||null});await WMFirebase.db.ref('adminProfiles/'+adminUser.uid).set({username,avatarUrl,updatedAt:firebase.database.ServerValue.TIMESTAMP});if(reserved&&oldKey){const oldRef=WMFirebase.db.ref('usernames/'+oldKey),oldValue=(await oldRef.once('value')).val();if(oldValue===adminUser.uid)await oldRef.remove()}showToast('Settings saved')}catch(error){if(reserved)await WMFirebase.db.ref('usernames/'+newKey).remove().catch(()=>{});showToast(error.message||'Unable to save settings')}}
  async function grantFreeProLive(){const input=document.getElementById('grantUser'),identity=input.value.trim().toLowerCase(),months=Number(document.getElementById('grantMonths').value);if(!identity){showToast('Enter an email or username');return}try{const user=users.find(item=>String(item.email||'').toLowerCase()===identity||String(item.name||'').toLowerCase()===identity);if(!user)throw new Error('User not found');const old=subscriptions[user.uid]||{},now=Date.now(),base=planFor(user.uid)==='pro'&&Number(old.expiresAt)>now?Number(old.expiresAt):now;let expiry=base;for(let index=0;index<months;index++)expiry=WMFirebase.addOneMonth(expiry);const proSince=old.proSince||now,normal=Number(pricing.normal||5),discount=Number(pricing.discount||0),monthlyPrice=discount>0&&discount<normal?discount:normal,supporterNumber=await nextSupporterNumber(old.supporterNumber);await Promise.all([WMFirebase.db.ref('subscriptions/'+user.uid).set({status:'pro',source:'free_grant',proSince,approvedAt:now,expiresAt:expiry,grantedMonths:months,monthlyPrice,grantedSubtotal:months*monthlyPrice,priceBasis:'locked',priceLockedAt:now,supporterNumber}),WMFirebase.db.ref('users/'+user.uid).update({proSince,proExpiresAt:expiry}),WMFirebase.db.ref('publicProfiles/'+user.uid).update({name:user.name||'User',avatarUrl:user.avatarUrl||'',downloads:Number(user.images||0)+Number(user.videos||0),showOnTopUsers:user.showOnTopUsers!==false,censorUsername:user.censorUsername===true,proSince,proExpiresAt:expiry})]);input.value='';showToast('Free Pro access granted until '+fullDate(expiry))}catch(error){showToast(String(error.message||'Unable to grant Pro').replace(/^Firebase:\s*/i,''))}}
  function stampGrantPricing(){if(!adminUser)return;Object.entries(subscriptions).forEach(([uid,sub])=>{if(sub?.source!=='free_grant'||sub.priceLockedAt||grantPricingStamped.has(uid))return;grantPricingStamped.add(uid);const months=Math.max(1,Number(sub.grantedMonths||1)),monthly=Number(pricing.normal||5),lockedAt=Number(sub.approvedAt||sub.proSince||Date.now());WMFirebase.db.ref('subscriptions/'+uid).update({monthlyPrice:monthly,grantedSubtotal:months*monthly,priceBasis:'locked',priceLockedAt:lockedAt}).catch(()=>grantPricingStamped.delete(uid))})}
  function recoverMissingEmails(){if(!adminUser)return;users.forEach(user=>{if(user.email||emailRecoveryStamped.has(user.uid))return;const payment=[...payments].reverse().find(item=>item.uid===user.uid&&item.email);if(!payment)return;user.email=String(payment.email).toLowerCase();emailRecoveryStamped.add(user.uid);WMFirebase.db.ref('users/'+user.uid+'/email').set(user.email).catch(()=>emailRecoveryStamped.delete(user.uid))})}
  async function backfillUsernameReservations(){if(!adminUser||usernameReservationsBackfilled||usernameReservationsBusy||!users.length)return;usernameReservationsBusy=true;try{const ordered=[...users].sort((a,b)=>earliestDate(a.accountCreatedAt,a.createdAt)-earliestDate(b.accountCreatedAt,b.createdAt));for(const user of ordered){const key=WMFirebase.usernameKey(user.name);if(!key)continue;await WMFirebase.db.ref('usernames/'+key).transaction(current=>current===null||current===user.uid?user.uid:undefined)}usernameReservationsBackfilled=true}catch(error){console.warn('Username reservation backfill deferred:',error.code||error.message)}finally{usernameReservationsBusy=false}}
  function renderNavCounters(){const button=document.querySelector('.admin-live-dashboard-nav button[data-admin-view="subscriptions"]');if(!button)return;let counter=button.querySelector('.admin-nav-counter');if(!counter){counter=document.createElement('span');counter.className='admin-nav-counter';button.appendChild(counter)}const pending=payments.filter(payment=>payment.status==='pending').length;counter.textContent=String(pending);counter.hidden=pending===0;counter.setAttribute('aria-label',pending+' pending payment'+(pending===1?'':'s'))}
  function renderAll(){stampGrantPricing();backfillSupporterNumbers();backfillUsernameReservations();recoverMissingEmails();renderIdentity();renderOverview();renderUsers();renderTop();renderSubscriptions();renderSettings();renderNavCounters()}
  function startListeners(){if(listenersStarted)return;listenersStarted=true;WMFirebase.db.ref('users').on('value',snapshot=>{users=[];snapshot.forEach(child=>users.push({uid:child.key,...child.val()}));users.sort((a,b)=>String(a.name||'').localeCompare(String(b.name||'')));renderAll()});WMFirebase.db.ref('subscriptions').on('value',snapshot=>{subscriptions=snapshot.val()||{};renderAll()});WMFirebase.db.ref('payments').on('value',snapshot=>{payments=[];snapshot.forEach(child=>payments.push({id:child.key,...child.val()}));renderAll()});WMFirebase.db.ref('settings/pricing').on('value',snapshot=>{const value=snapshot.val()||{},normal=Number(value.normal||5),discount=value.discount==null?null:Number(value.discount);pricing={normal,discount:discount>0&&discount<normal?discount:null};renderAll()});WMFirebase.db.ref('settings/adminAvailable').on('value',snapshot=>{adminAvailable=snapshot.val()!==false;const button=document.getElementById('adminAvailabilityToggle');if(button){button.classList.toggle('on',adminAvailable);button.querySelector('span').textContent=adminAvailable?'Available':'Unavailable'}});WMFirebase.db.ref('settings/paymentQrUrl').on('value',snapshot=>{const url=snapshot.val()||'qr.jpg';const input=document.getElementById('adminQrUrl');if(input)input.value=url;previewAdminQr(url)});WMFirebase.db.ref('adminProfiles/'+adminUser.uid).on('value',snapshot=>{adminProfile=snapshot.val()||{};renderAll()})}
  function stopAdminListeners(){['users','subscriptions','payments','settings/pricing','settings/adminAvailable','settings/paymentQrUrl'].forEach(path=>WMFirebase.db.ref(path).off());if(adminUser?.uid)WMFirebase.db.ref('adminProfiles/'+adminUser.uid).off();listenersStarted=false}
  document.addEventListener('DOMContentLoaded',()=>{createShell();showView((location.hash||'#overview').slice(1));WMFirebase.auth.onAuthStateChanged(async user=>{const header=document.querySelector('.admin-live-header');if(!user){adminUser=null;adminProfile={};users=[];publicProfiles={};subscriptions={};payments=[];selectedUid=null;document.querySelector('.admin-live-menu')?.setAttribute('hidden','');document.querySelectorAll('.modal.show,.admin-confirm-overlay.show').forEach(node=>node.classList.remove('show'));header.style.display='none';document.documentElement.classList.remove('admin-settings-view','admin-booting');return}const allowed=(await WMFirebase.db.ref('admins/'+user.uid).once('value')).val()===true;if(!allowed){document.documentElement.classList.remove('admin-booting');return}adminUser=user;header.style.display='block';startListeners();renderAll();document.documentElement.classList.remove('admin-booting')})});
})();
