const fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const {DatabaseSync}=require('node:sqlite');
const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
(async()=>{
 const db=new DatabaseSync(':memory:');
 db.exec(`PRAGMA foreign_keys=ON;
 CREATE TABLE users(id TEXT PRIMARY KEY,username TEXT UNIQUE,email TEXT UNIQUE,password_hash TEXT,password_salt TEXT,role TEXT,photo TEXT,plan TEXT,status TEXT,created_at TEXT,pro_until TEXT,downloads_images INTEGER DEFAULT 0,downloads_videos INTEGER DEFAULT 0,public_profile INTEGER DEFAULT 1);
 CREATE TABLE sessions(token_hash TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),created_at TEXT,expires_at TEXT);
 CREATE TABLE settings(id INTEGER PRIMARY KEY,admin_username TEXT,admin_photo TEXT,payments_open INTEGER,qr_image TEXT,whatsapp TEXT,auth_banners TEXT,overview_banners TEXT,community_url TEXT);
 CREATE TABLE plans(id TEXT,slug TEXT,name TEXT,normal_price REAL,discount_price REAL,discount_label TEXT,billing_label TEXT,description TEXT,features_json TEXT,active INTEGER);
 CREATE TABLE submissions(id TEXT PRIMARY KEY,user_id TEXT,username TEXT,email TEXT,plan_name TEXT,reference TEXT UNIQUE,amount REAL,payment_time TEXT,submitted_at TEXT,status TEXT);
 CREATE TABLE subscriptions(id TEXT,user_id TEXT,username TEXT,plan_name TEXT,reference TEXT,receipt_no TEXT,amount REAL,months INTEGER,starts_at TEXT,ends_at TEXT,created_at TEXT,payment_time TEXT,status TEXT);
 CREATE TABLE notifications(id TEXT PRIMARY KEY,title TEXT,text TEXT,audience TEXT,sender_username TEXT,sender_photo TEXT,created_at TEXT);
 CREATE TABLE legal_sections(id TEXT,type TEXT,title TEXT,text TEXT,position INTEGER,updated_at TEXT);`);
 function statement(sql,args=[]){const s=db.prepare(sql);return{bind(...a){return statement(sql,a)},async first(){return s.get(...args)||null},async all(){return{results:s.all(...args)}},async run(){const r=s.run(...args);return{meta:{changes:r.changes}}},_sql:sql,_args:args};}
 const env={DB:{prepare:statement,async batch(stmts){db.exec('BEGIN');try{const out=stmts.map(s=>{const p=db.prepare(s._sql);if(/^\s*SELECT/i.test(s._sql))return{results:p.all(...s._args)};return{meta:{changes:p.run(...s._args).changes}}});db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}}};
 const worker=(await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync('worker.js','utf8')).toString('base64'))).default;
 let origin='http://test.invalid';env.ALLOWED_ORIGINS=origin;
 async function req(url,method='GET',body,token){const r=await worker.fetch(new Request(origin+url,{method,headers:{'Content-Type':'application/json',Origin:origin,...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})}),env);return{status:r.status,data:await r.json()};}
 let r=await req('/api/auth/register','POST',{username:'debuguser',email:'debug@example.invalid',password:'Debug-password-2026'});if(r.status!==201)throw new Error('register '+JSON.stringify(r));const user=r.data.user;
 db.prepare("INSERT INTO settings VALUES(1,'@admin','',1,'','','[]','[]','')").run();db.prepare("INSERT INTO plans VALUES('pro','pro','Pro',12,4,'','bulan','','[]',1)").run();
 db.prepare("INSERT INTO users SELECT 'admin','@admin','admin@example.invalid',password_hash,password_salt,'admin','','pro','active',created_at,NULL,0,0,1 FROM users WHERE id=?").run(user.id);
 const avatarBytes=fs.readFileSync('logo.jpg');db.prepare('UPDATE users SET photo=?,downloads_images=999999 WHERE id=?').run('https://uploadsimage.org/i/debug.png',user.id);const originalFetch=globalThis.fetch;globalThis.fetch=async(url,options)=>String(url)==='https://uploadsimage.org/i/debug.png'?new Response(avatarBytes,{headers:{'Content-Type':'image/jpeg'}}):originalFetch(url,options);
 r=await req('/api/auth/login','POST',{email:'admin@example.invalid',password:'Debug-password-2026',adminOnly:true});if(r.status!==200)throw new Error('admin login '+JSON.stringify(r));const admin=r.data.token;
 const server=http.createServer(async(incoming,out)=>{try{const u=new URL(incoming.url,'http://x');if(u.pathname.startsWith('/api/')){const chunks=[];for await(const c of incoming)chunks.push(c);const q=await worker.fetch(new Request(origin+incoming.url,{method:incoming.method,headers:{...Object.fromEntries(Object.entries(incoming.headers).filter(([k])=>k!=='host')),Origin:origin},...(chunks.length?{body:Buffer.concat(chunks)}:{})}),env);out.writeHead(q.status,Object.fromEntries(q.headers));out.end(Buffer.from(await q.arrayBuffer()));return}let rel=u.pathname.replace(/^\//,'')||'control.html';if(rel==='control'||rel==='control/')rel='control.html';const file=path.resolve(__dirname,rel);if(!file.startsWith(__dirname)||!fs.existsSync(file)){out.writeHead(404);return out.end()}const ext=path.extname(file);out.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.jpg':'image/jpeg','.png':'image/png','.webmanifest':'application/manifest+json'})[ext]||'text/plain'});out.end(fs.readFileSync(file));}catch(e){out.writeHead(500);out.end(e.stack)}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin='http://127.0.0.1:'+server.address().port;env.ALLOWED_ORIGINS=origin;
 const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage();p.on('console',m=>console.log('console',m.type(),m.text()));p.on('pageerror',e=>console.log('pageerror',e.message));p.on('download',d=>console.log('DOWNLOAD',d.suggestedFilename()));
 await p.addInitScript(base=>window.WATERMARK_API_BASE=base,origin);await p.addInitScript(t=>localStorage.setItem('watermarkProControlApiToken',t),admin);await p.route('https://uploadsimage.org/**',route=>route.fulfill({contentType:'image/jpeg',body:avatarBytes}));await p.goto(origin+'/control.html');await p.waitForFunction(()=>window.WPControl?.state?.users?.length>0);
 console.log('state',await p.evaluate(()=>({users:window.WPControl.state.users.length,button:document.querySelector('#downloadTopUsers')?.outerHTML,rect:document.querySelector('#downloadTopUsers')?.getBoundingClientRect().toJSON(),disabled:document.querySelector('#downloadTopUsers')?.disabled,status:document.querySelector('#controlExportStatus')?.textContent||'',api:window.WPControlCloudflare?.apiBase})));
 await p.evaluate(()=>{const old=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){console.log('ANCHOR_CLICK',this.download,this.isConnected);return old.call(this)}});
 await p.locator('#downloadTopUsers').click({timeout:5000});await p.waitForTimeout(5000);
 console.log('after',await p.evaluate(()=>({status:document.querySelector('#controlExportStatus')?.textContent||'',button:document.querySelector('#downloadTopUsers')?.outerHTML,users:window.WPControl?.state?.users?.length})));
 await b.close();server.close();db.close();
})().catch(e=>{console.error(e);process.exitCode=1});
