(()=>{
 document.documentElement.style.setProperty('--wp-wmark-image','url("'+window.WPWMarkAsset+'")');
 const nameLayout=document.createElement('style');nameLayout.textContent='.identity-copy strong{overflow:visible!important}.identity-copy strong .control-wmark{flex-shrink:0!important}.identity-copy{overflow:visible!important}.top-user-row .identity-copy strong{white-space:normal!important;overflow-wrap:anywhere}.top-user-row .identity{min-width:0!important}';document.head.append(nameLayout);
 const errorLayout=document.createElement('style');errorLayout.textContent='#controlExportStatus{display:block!important;flex:0 0 100%!important;width:100%!important;grid-column:1/-1!important;padding:12px!important;margin:12px 0 0!important;border-radius:10px;background:#fff3f3;color:#9d2525;font-size:13px;line-height:1.5}';document.head.append(errorLayout);
 window.WPControlExportError=error=>{let status=document.getElementById('controlExportStatus');if(!status){status=document.createElement('p');status.id='controlExportStatus';status.setAttribute('role','status');document.getElementById('downloadTopUsers')?.parentElement.after(status)}console.error('Control PNG export:',error);status.textContent=error.userMessage||'Imej belum dapat dimuat turun. Cuba sekali lagi. Jika masih gagal, buka Pusat Kawalan melalui laman web dan cuba semula.'};
 const layout=document.createElement('style');layout.textContent='.sidebar .nav{align-content:start!important;grid-auto-rows:44px!important;gap:5px!important}.sidebar .navbtn{height:44px!important;min-height:44px!important}';document.head.append(layout);
 const section=document.createElement('section');section.id='resetPasswordSection';section.hidden=true;section.className='modal-body';
 layout.textContent+='.user-row{column-gap:24px!important}.identity,.identity-copy{min-width:0!important}.identity-copy strong{max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.top-user-row{grid-template-columns:auto minmax(0,1fr) auto!important;gap:16px!important}.top-user-count{min-width:72px;flex-shrink:0}.user-row>.identity{padding-right:12px;box-sizing:border-box}@media(max-width:600px){.top-user-row{gap:10px!important}.top-user-row .identity-copy strong{font-size:13px!important}.top-user-count{min-width:64px}.top-user-count strong{overflow-wrap:anywhere}}';
 section.innerHTML='<h3>Tetapkan semula kata laluan</h3><form id="resetPasswordForm" novalidate><div class="field"><label for="resetUserPassword">Kata laluan baharu</label><input id="resetUserPassword" type="password" autocomplete="new-password"></div><p id="resetUserPasswordStatus" role="status" aria-live="polite"></p><button id="resetUserPasswordBtn" class="btn" type="submit">Simpan kata laluan baharu</button></form>';
 document.querySelector('#userModal .modal-shell').append(section);
 const style=document.createElement('style');style.textContent='.identity-copy strong{display:inline-flex;align-items:center;gap:3px}.control-wmark{width:13px;height:auto;flex:0 0 13px}.password-toggle{margin-top:6px;font-size:12px}';document.head.append(style);
 document.querySelectorAll('input[type="password"]').forEach(input=>{const b=document.createElement('button');b.type='button';b.className='btn small password-toggle';b.textContent='Papar kata laluan';b.setAttribute('aria-pressed','false');input.after(b);b.onclick=()=>{const show=input.type==='password';input.type=show?'text':'password';b.textContent=show?'Sorok kata laluan':'Papar kata laluan';b.setAttribute('aria-pressed',String(show))}});
 const b=document.getElementById('resetUserPasswordBtn');if(!b)return;document.getElementById('resetPasswordForm').onsubmit=async event=>{
  event.preventDefault();
  const id=document.getElementById('userId').value,input=document.getElementById('resetUserPassword'),status=document.getElementById('resetUserPasswordStatus');
  if(!id)return;
  b.disabled=true;status.textContent='Menyimpan…';
  try{const r=await window.WPControlCloudflare.resetPassword(id,input.value);input.value='';input.type='password';status.textContent=r.message;}catch(e){status.textContent=e.message||'Gagal menyimpan.';}finally{b.disabled=false;}
 };
})();
